### PR TITLE
Retrieve instance id instead of public_id in terminal output

### PR DESCRIPTION
**Pull request by Ghesselink**
The instance id doesn't need to be obfuscated for the Gherkin terminal output

### CODE REVIEW

**Comment by aothms** [comment]
This is not the numeric stepfile id, but the foreign key into the instances table in our internal DB. Or at least, that's what it should be. I believe this should still be obfuscated.

**Comment by Ghesselink** [comment]
Are you sure? This applies to the `.to_dict` that we're using to pass the outcome to the custom JSON wile testing Gherkin. Before the change, we got a obfuscated number. 
image

If we return the instance_id, we get the following outcome 
image

This suggests that `instance_id` it's indeed the stepfile id.

I remember these ids were often missing from the outcome in the platform as well, so I think there is some confusion in the code somewhere..

**Comment by aothms** [comment]
https://github.com/buildingSMART/ifc-validation-data-model/blob/6dc5e001bfd5dd9a92abf23e5ba2bf186067e4e3/models.py#L581-L586

But you're right, there is also a point in time when we use that id as the step file id and then later transform it properly in the database.

https://github.com/buildingSMART/validate/blob/0c9190576836958a1295f2c3845228f0d1e716fc/backend/apps/ifc_validation/tasks.py#L721-L724

So somehow your change needs to be more local to the testing code paths I think.

**Comment by civilx64** [comment]
This PR doesn't provide any tangible benefit to the end user and hints at a lack of separation between applicaton logic and data storage within our system design.  I vote that we close this PR and focus on wrapping up outstanding items for v0.6.7.

**Pull request closed without merging**
