### PR TITLE
IVS-135 Functional Parts to datamodel (VS Scorecards)

### PR DESCRIPTION
**Pull request by Ghesselink**
In combination with https://github.com/buildingSMART/ifc-gherkin-rules/pull/291 . 
I've added the tag hierarchy to the datamodel. However, we still wouldn't have enough information to colour the blocks for each functional parts (the feature name itself does not suffice). Therefore, I've also included this info in the data model. This allows us to retrieve the functional parts along with their sub-parts or parent parts directly from each instance of ValidationOutcome.

Usage:
1) **As a Static Class**:
    - **Retrieve Hierarchy**: 
        Retrieve the complete hierarchy of a functional part without needing to instantiate the `FunctionalPart` class.
        ```python
        hierarchy = FunctionalPart.get_hierarchy('GEM')
        # {
        #   'code': 'GEM', 
        #   'name': 'Geometry representation', 
        #   'sub_parts': [{'code': 'TAS', ...}, {'code': 'SWE', ...}, ...]
        # }
        ```
        This returns an overview of the entire hierarchy of the functional part with the code `'GEM'`, including all its subparts with their respective codes and descriptions.

    - **Get Sub-part Codes**:
        Retrieve only the codes of the sub-parts of a functional part.
        ```python
        sub_part_codes = [i['code'] for i in FunctionalPart.get_hierarchy('GEM')['sub_parts']]
        # ['TAS', 'SWE', 'MPD', 'BRP', 'TFM', 'BBX', 'RCO', 'CPD', 'ALS']
        ```

    - **Get Parent of a Sub-part**:
        Retrieve the parent of a specific functional part by its code.
        ```python
        parent = FunctionalPart.get_parent('ALS')
        # {'code': 'GEM', 'name': 'Geometry representation'}
        ```

2) **Within the Context of `ValidationOutcome`**:
    - **Storing Functional Parts**:
        When creating a `ValidationOutcome`, functional parts can be associated with it via the `functional_part_codes` attribute.
        ```python
        validation_outcome = ValidationOutcome(
            # Other attributes...
            functional_part_codes=FunctionalPart.filter_functional_part_tags(context.tags)
        )
        ```
        The `filter_functional_part_tags` method filters and retrieves relevant functional parts from the tags present in the Behave context (i.e. `context.feature.tags`).

    - **Accessing Functional Parts**:
        Once a `ValidationOutcome` instance is created, it's possible to ccess the associated functional parts along with their relevant information.
        ```python
        validation_outcome.functional_parts
        # [<FunctionalPart: ALS - Alignment geometry>, <FunctionalPart: GEM - Geometry representation>]
        ```

    - **Navigating Functional Part Hierarchies**:
        From each `FunctionalPart` in `validation_outcome.functional_parts`:
        - Get the parent of the functional part:
          ```python
          validation_outcome.functional_parts[0].parent
          # <FunctionalPart: GEM - Geometry representation>
          ```
        - Retrieve all possible sub-parts:
          ```python
          validation_outcome.functional_parts[1].sub_parts
          # [<FunctionalPart: TAS - Tessellated (i.e., meshes)>, <FunctionalPart: SWE - Sweeps (i.e., extrusions, lofts, blends)>, ...]
          ```

### CODE REVIEW

**Comment by aothms** [comment]
> the feature name itself does not suffice

Can you elaborate on that. I assumed `feature_name[0:3]` is the functional part. It's not a direct logical link as in a foreign key in the DB, but I thought for the first version it'd be good enough.

Recording things in the database makes us a little bit less flexible in the prototypical stage because we can't easily adjust things that are already materialized in the DB and can't use the existing outcomes in the DB for testing because they don't have this new field.

In the long run I'm quite sure we'll have some Admin+DB interface to all of this. I'm just questioning whether we need it now and wouldn't slow us down.

**Comment by Ghesselink** [comment]
> Can you elaborate on that.

When a feature is called `'ALB000_Some_Rule'`, we're also including it's 'parent';` 'POS'.` There's no direct way of obtaining this info from it's name. We can work around with a simple lookup of tags with their respective sub_tags / sub_functional_parts, similar as in the PR in the gherkin repo. For example, [like this](https://github.com/buildingSMART/ifc-validation-data-model/pull/22). 

The feature PJS002 contains two tags / references to functional part; `PJS` and `BLT`. How do we know from the feature name that we're also checking for the Built Elements? 

Furthermore, the rule we discussed yesterday (ALB016) will have four tags 
`@POS @ALB @OJP @LIP`
When calling the feature` 'ALB016 - Alignment Local Placement' ` two functional part that will be included in the scorecards will be known by simply looking at the tag hierarchy (`POS` being the 'parent' of `ALB`). This is not the case for `OJP` and `LIP`. 

I'm fine with adding a simple enumeration to data-model repo to lookup tag_hierarchies. For example, [like this.](https://github.com/buildingSMART/ifc-validation-data-model/pull/22) That is maybe sufficient for the scorecards demo. 

Another option would be to parse the feature file itself. This creates issues with versioning however. 

Or perhaps there is something simpler that I haven't thought.

**Comment by aothms** [comment]
> we're also including it's 'parent'; 'POS'. 

Ok, but here is still a legitimate other approach that instead of materializing that data in the DB, instead we account for this when rendering the score cards **post aggregation**.

I don't see an advantage of listing the superparts in the DB/featurefile. It only makes things slightly less flexible.

> The feature PJS002 contains two tags / references to functional part; PJS and BLT. How do we know from the feature name that we're also checking for the Built Elements?

Yeah, thanks for holding my hand here, this I wasn't really aware of. I think I always advised against this though. This is confusing to end users and to ourselves.

In the case of PJS002:

```
@PJS
@BLT
Feature: PJS002 - Correct elements related to project
```

**features/resources/valid_ProjectDeclaration.csv**

```
IfcActor
IfcControl
IfcGroup
IfcProcess
IfcProjectLibrary
IfcPropertySetTemplate
IfcResource
```

By means of elimination, sure there is a chance that when it's not in the above list, it's a built element, but it's not the only possibility. It could be a IfcPropertySet for example.

afbeelding

In this case I'd say this is clearly only PJS002 or otherwise, we need to make it much more precise from the relatedobjects end how we allocate this.

> Furthermore, the rule we discussed yesterday (ALB016) will have four tags `@POS @ALB @OJP @LIP`

You could, but I don't understand why. This means that one rule has the ability to color 4 boxes red. `POS/ALB` is clear, but `LIP` *The ability to define the placement of a product in relation to a curve.* is not really asserted here as this is more about the placement of the curve/alignment itself. Similarly `OJP` *The ability to define the location, orientation, and scale of built elements and systems within the building model.* I also don't see that as relevant, even if the alignment is forced to use IfcObjectPlacement. I think the intent behind this rule is 100% covered by `ALB` (and it's superpart `POS`).

I'm picking on the individual examples here, but my main argument is simplicity. If we have a tree of `SuperPart > Part > Rule` things are clear. I think we always had that in mind, that's why are rules are named based on one functional part. The fact that we **can** tag multiple rules doesn't mean that we **should**.

cc @evandroAlfieri @civilx64

**Comment by Ghesselink** [comment]
> but my main argument is simplicity

Agree. In that case, we can derive the superpart (or subpart) post-aggregation from a simply Enum in the datamodel repo (i.e. no extra entries or modifications in the db). Something like [this](https://github.com/buildingSMART/ifc-validation-data-model/pull/22), perhaps even simpler. 

> In this case I'd say this is clearly only PJS002 or otherwise, we need to make it much more precise from the relatedobjects end how we allocate this.

We have many options now in Gherkin to verbalise precisely what we're testing for. For example, by explicitly including or excluding inheritance during the selection of activating instance (i.e. in Given statements). So in this case, we also have the option to just create another rule with its own feature file and tags. 
That seems like the clearer/more explicit approach; If the rule applies to multiple functional parts, create a separate rule to reflecting these nuances.

**Comment by evandroAlfieri** [comment]
I can only partially follow. My 2 cents:
- parent-child relationship kept elsewhere for flexibility. Not in db, not in feature files (I know I had the opposite view on this last one, changed my mind). 
- multiple tagging allowed and used when we believe that failing the given rule will result in not supporting all features tagged in the rule. Example: failing a rule on the linear placement of referents means that the tool's implementations of linear placement and of referents are both inaccurate.

**Comment by aothms** [comment]
I've added this to todays agenda :)

> multiple tagging allowed and used when we believe that failing the given rule will result in not supporting all features tagged in the rule. Example: failing a rule on the linear placement of referents means that the tool's implementations of linear placement and of referents are both inaccurate.

I still don't see this as a valid example. These I think are two rules:

- Given a linear placement ... Then it should be valid
- Given a referent ... Then it should be linearly positioned

From the beginning onwards we identified there are "Mechanisms" (like linear placement) and "Domain-specific products" (a wall, a window). We really should be careful that we're not mixing these two and create a combinatorial explosion of every mechanism applied to every type of product. A rule should either test whether a mechanism is correctly applied or whether a domain specific product is correct configured, but not both at the same time.

Currently this is also really too confusing for end-users I think. As we agreed previously: generally, people will only read the rule title. This includes ALB016, people will recognize the ALB part. How will they ever find out that this has an impact on the `OJP` box? This last part is solvable in the UI of course.

If we remain on this route I would do it differently in the datamodel. Currently we have `feature` as an attribute in the data model. If we go this far I would say we create a `feature` table in the DB and create a foreign key to that. That's also a nicer stepping stone towards a failing step reference in the DB. Maybe I'm being overly cautious but we have a lot of outcomes in the DB. I think we should apply some normalization to that and not store all functional parts **per outcome**. So that means we either:

- simplify: functional part is identical to first 3 characters from feature name
- normalize storage: move more information from the validation_outcome table to a new feature table.

**Comment by Ghesselink** [comment]
Superceded by certification datamodel

**Pull request closed without merging**
